// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sanctuary.Database;

#nullable disable

namespace Sanctuary.Database.Sqlite.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240622125113_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("DbItemDbProfile", b =>
                {
                    b.Property<int>("ItemsId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ItemsCharacterGuid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfilesId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ProfilesCharacterGuid")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemsId", "ItemsCharacterGuid", "ProfilesId", "ProfilesCharacterGuid");

                    b.HasIndex("ProfilesId", "ProfilesCharacterGuid");

                    b.ToTable("ProfileItems", (string)null);
                });

            modelBuilder.Entity("Sanctuary.Database.Entities.DbCharacter", b =>
                {
                    b.Property<ulong>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActiveTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatBubbleBackgroundColor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(13951728);

                    b.Property<int>("ChatBubbleForegroundColor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(408679);

                    b.Property<int>("ChatBubbleSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE()");

                    b.Property<int>("EyeColor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FacePaint")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hair")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HairColor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Head")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("MembershipStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Model")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelCustomization")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkinTone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Ticket")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserGuid")
                        .HasColumnType("INTEGER");

                    b.Property<float>("VipRank")
                        .HasColumnType("REAL");

                    b.ComplexProperty<Dictionary<string, object>>("Position", "Sanctuary.Database.Entities.DbCharacter.Position#Vector4", b1 =>
                        {
                            b1.Property<float>("W")
                                .HasColumnType("REAL");

                            b1.Property<float>("X")
                                .HasColumnType("REAL");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL");

                            b1.Property<float>("Z")
                                .HasColumnType("REAL");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Rotation", "Sanctuary.Database.Entities.DbCharacter.Rotation#Quaternion", b1 =>
                        {
                            b1.Property<float>("W")
                                .HasColumnType("REAL");

                            b1.Property<float>("X")
                                .HasColumnType("REAL");

                            b1.Property<float>("Y")
                                .HasColumnType("REAL");

                            b1.Property<float>("Z")
                                .HasColumnType("REAL");
                        });

                    b.HasKey("Guid");

                    b.HasIndex("UserGuid");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Sanctuary.Database.Entities.DbItem", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CharacterGuid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE()");

                    b.Property<int>("Definition")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tint")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "CharacterGuid");

                    b.HasIndex("CharacterGuid");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Sanctuary.Database.Entities.DbMount", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CharacterGuid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE()");

                    b.Property<bool>("IsUpgraded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "CharacterGuid");

                    b.HasIndex("CharacterGuid");

                    b.ToTable("Mounts");
                });

            modelBuilder.Entity("Sanctuary.Database.Entities.DbProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CharacterGuid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LevelXP")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "CharacterGuid");

                    b.HasIndex("CharacterGuid");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Sanctuary.Database.Entities.DbTitle", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("CharacterGuid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id", "CharacterGuid");

                    b.HasIndex("CharacterGuid");

                    b.ToTable("Titles", (string)null);
                });

            modelBuilder.Entity("Sanctuary.Database.Entities.DbUser", b =>
                {
                    b.Property<ulong>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("DATE()");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMember")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxCharacters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Session")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Guid = 1ul,
                            Created = new DateTimeOffset(new DateTime(2024, 6, 22, 13, 51, 13, 273, DateTimeKind.Unspecified).AddTicks(6902), new TimeSpan(0, 1, 0, 0, 0)),
                            IsAdmin = true,
                            IsLocked = false,
                            IsMember = true,
                            MaxCharacters = 10,
                            Password = "admin",
                            Session = "EXmdPd5dbAcs58vZ0iCcPRtJkGdMePL2",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("DbItemDbProfile", b =>
                {
                    b.HasOne("Sanctuary.Database.Entities.DbItem", null)
                        .WithMany()
                        .HasForeignKey("ItemsId", "ItemsCharacterGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sanctuary.Database.Entities.DbProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfilesId", "ProfilesCharacterGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanctuary.Database.Entities.DbCharacter", b =>
                {
                    b.HasOne("Sanctuary.Database.Entities.DbUser", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sanctuary.Database.Entities.DbItem", b =>
                {
                    b.HasOne("Sanctuary.Database.Entities.DbCharacter", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Sanctuary.Database.Entities.DbMount", b =>
                {
                    b.HasOne("Sanctuary.Database.Entities.DbCharacter", "Character")
                        .WithMany("Mounts")
                        .HasForeignKey("CharacterGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Sanctuary.Database.Entities.DbProfile", b =>
                {
                    b.HasOne("Sanctuary.Database.Entities.DbCharacter", "Character")
                        .WithMany("Profiles")
                        .HasForeignKey("CharacterGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Sanctuary.Database.Entities.DbTitle", b =>
                {
                    b.HasOne("Sanctuary.Database.Entities.DbCharacter", "Character")
                        .WithMany("Titles")
                        .HasForeignKey("CharacterGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Sanctuary.Database.Entities.DbCharacter", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Mounts");

                    b.Navigation("Profiles");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("Sanctuary.Database.Entities.DbUser", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
