<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <TargetFramework>$(TargetFramework)</TargetFramework>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sanctuary.Game\Sanctuary.Game.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Resources\CollectionNodePools.json" Link="Resources\CollectionNodePools.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\Resources\CollectionNodeSpawns.json" Link="Resources\CollectionNodeSpawns.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\Resources\CollectionNodeTypes.json" Link="Resources\CollectionNodeTypes.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
